// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// sharedHead renders the common <head> element for every admin page.
// All shared and page-specific CSS lives here so there is a single source
// of truth for the design system.
func sharedHead(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/admin/ui/layout.templ`, Line: 10, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css\"><script src=\"https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js\"></script><style>\n\t\t\t/* ── state badges ─────────────────────────────── */\n\t\t\t.state-badge {\n\t\t\t\tdisplay: inline-block;\n\t\t\t\tpadding: 0.15em 0.6em;\n\t\t\t\tborder-radius: 999px;\n\t\t\t\tfont-size: 0.75em;\n\t\t\t\tfont-weight: 600;\n\t\t\t\ttext-transform: uppercase;\n\t\t\t\tletter-spacing: 0.05em;\n\t\t\t}\n\t\t\t.state-connected  { background: #1a4731; color: #6fcf97; }\n\t\t\t.state-connecting { background: #4a3000; color: #f2c94c; }\n\t\t\t.state-error      { background: #4a1010; color: #eb5757; }\n\n\t\t\t/* ── annotation badges (detail page) ─────────── */\n\t\t\t.badge-readonly    { background: #1a4731; color: #6fcf97; }\n\t\t\t.badge-idempotent  { background: #1a2f50; color: #5dade2; }\n\t\t\t.badge-destructive { background: #4a1010; color: #eb5757; }\n\n\t\t\t/* ── utility ─────────────────────────────────── */\n\t\t\t.dim         { opacity: 0.55; font-size: 0.85em; }\n\t\t\t.panel-header { display: flex; justify-content: space-between; align-items: center; }\n\n\t\t\t/* ── detail page ─────────────────────────────── */\n\t\t\t.meta-chips { display: flex; gap: 1.25rem; align-items: center; flex-wrap: wrap; }\n\t\t\t.tool-header {\n\t\t\t\tdisplay: flex;\n\t\t\t\tjustify-content: space-between;\n\t\t\t\talign-items: flex-start;\n\t\t\t\tgap: 1rem;\n\t\t\t\tflex-wrap: wrap;\n\t\t\t}\n\t\t\t.badge-row   { display: flex; gap: 0.4rem; flex-wrap: wrap; }\n\t\t\ttable.params { font-size: 0.85em; }\n\t\t\ttable.params td, table.params th { white-space: nowrap; }\n\t\t\ttable.params td:last-child        { white-space: normal; }\n\t\t</style></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
